### ISSUE TITLE
band.get_activity_betwn_intervals() => bluepy.btle.BTLEInternalError: Unexpected response (wr)

### ISSUE THREAD

**Issue by janvda** [janvda/miband4#6]
When retrieving activity log getting below error:

```
2021-11-27 22:50:16,508 miband_api (DEBUG) > retrieve_activity(): acquiring lock ...
2021-11-27 22:50:16,509 miband_api (INFO) > Calling retrieve_activity() ...
2021-11-27 22:50:16,510 miband_api (INFO) > retrieving activity between 2021-11-27 20:50:00 and 2021-11-27 22:45:00
2021-11-27 22:50:16,510 miband (DEBUG) > start_get_previews_data(2021-11-27 20:50:00)...
2021-11-27 22:50:16,512 miband_api (DEBUG) > retrieve_activity():...lock released
2021-11-27 22:50:16,514 uvicorn.access (INFO) > 172.25.0.2:42394 - "POST /retrieve_activity?start_time_ms=1638042600000&end_time_ms=1638049500000 HTTP/1.1" 500
2021-11-27 22:50:16,515 uvicorn.error (ERROR) > Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 805, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 743, in run
    result = func(*args)
  File "/miband4/miband_api.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/miband4/miband_api.py", line 46, in wrapper
    rc=func(*args, **kwargs)
  File "/miband4/miband_api.py", line 255, in retrieve_activity
    return band.get_activity_betwn_intervals(start_time,end_time,cb_activity_log)
  File "/miband4/miband.py", line 569, in get_activity_betwn_intervals
    self.start_get_previews_data(start_timestamp)
  File "/miband4/miband.py", line 562, in start_get_previews_data
    utc_offset = char.read()[9:11]
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 197, in read
    return self.peripheral.readCharacteristic(self.valHandle)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 530, in readCharacteristic
    resp = self._getResp('rd')
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 375, in _waitResp
    raise BTLEInternalError("Unexpected response (%s)" % respType, resp)
bluepy.btle.BTLEInternalError: Unexpected response (wr)
2021-11-27 22:55:16,498 miband_api (DEBUG) > retrieve_activity(): acquiring lock ...
```

**Comment by janvda** [comment]
bluepy  (version 1.3.0) is not threadsafe when reading/writing from a specific characteristic.
One thread could receive the response for a read/write request that was meant for the other thread and most likely this is causing above error.

A solution for this might be posting in that case the event back on the queue as specified by:
*  IanHarvey/bluepy@2045c34

**Comment by janvda** [comment]
I would propose a simple solution where we exit() the process so that docker restarts the container.

**Comment by janvda** [comment]
we will exit() in that case as => see https://github.com/janvda/miband4/commit/64a5c5344df6eb04d6ad911b56cb5b8aa2a183cd
